# Topic: Missing values (Data cleaning)

In this lecture, we will learn how to **detect** and **handle** missing values in Pandas using **`customer.csv`**.

We will cover:
- `isna()` (detect missing values)
- `dropna()` (remove rows with missing values)
- `fillna()` (replace missing values) using the **mean**
- Practice problems (with answers)

## Load `customer.csv`

✅ If `customer.csv` is in the same folder as this notebook, the first option works.

(Your uploaded file might be named `customer (5).csv`, so the code below also tries that.)

In [6]:
# mount google drive

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [7]:
import pandas as pd

In [8]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Teaching/4510/LectureNote/Pandas-Data-Management/customer.csv")

df.head()

,CustID,Sex,Race,BirthDate,College,HouseholdSize,ZipCode,Income,Spending2020,Spending2021,NumOfOrders,DaysSinceLast,Satisfaction,Channel
0,1530016,Female,Black,12/16/1986,Yes,5,90047,53000,287.0,241.0,3,101,Very Dissatisfied,SM
1,1531136,Male,White,5/9/1993,Yes,5,90026,94000,1227.0,843.0,12,262,Neutral,TV
2,1532160,Male,Black,5/22/1966,Yes,2,90027,64000,523.0,719.0,9,122,Very Satisfied,TV
3,1532307,Male,White,9/16/1964,Yes,4,90029,60000,516.0,582.0,13,129,Very Dissatisfied,SM
4,1532356,Female,Hispanic,7/15/1964,No,5,90017,47000,555.0,845.0,7,97,Very Dissatisfied,Web

In [9]:
# (rows, columns)
df.shape

(219, 14)

In [ ]:
# Quick numeric summary
df.describe()

,CustID,HouseholdSize,ZipCode,Income,Spending2020,Spending2021,NumOfOrders,DaysSinceLast
count,2.190000e+02,219.000000,219.000000,219.000000,212.000000,214.000000,219.000000,219.000000
mean,1.557781e+06,3.086758,90034.068493,73036.529680,644.962264,648.607477,10.844749,184.958904
std,1.424019e+04,1.429300,18.970519,24060.293889,396.516608,348.058526,9.329523,100.830374
min,1.530016e+06,1.000000,90001.000000,31000.000000,42.000000,50.000000,1.000000,6.000000
25%,1.546122e+06,2.000000,90018.000000,54000.000000,331.750000,372.500000,4.000000,102.000000
50%,1.557181e+06,3.000000,90032.000000,70000.000000,587.500000,626.000000,9.000000,181.000000
75%,1.571437e+06,4.000000,90050.000000,91500.000000,883.250000,943.250000,15.000000,266.000000
max,1.579979e+06,5.000000,90068.000000,167000.000000,1851.000000,1250.000000,89.000000,360.000000

## Missing values in Pandas

In Pandas, missing values are commonly stored as **NaN**.  
`isna()` helps us find missing values by returning **True/False**.

## Detect missing values (ONE column)

### `df["Spending2020"].isna()` returns True/False

In [13]:
#df["Spending2020"] column subsetting
df["Spending2020"].isna()  #True --> missing value
                           #False --> no missing value

0      False
1      False
2      False
3      False
4      False
       ...
214     True
215    False
216    False
217    False
218    False
Name: Spending2020, Length: 219, dtype: bool

### Count missing values in one column using `sum()`

✅ `True` behaves like 1, `False` behaves like 0, so `sum()` counts missing values.

In [15]:
df["Spending2020"].isna().sum()

np.int64(7)

In [19]:
#count # of missing values in the column,  Income
df["Income"].isna().sum()

np.int64(0)

## Detect missing values (MULTIPLE columns)

✅ **Important:** multiple columns must use **double square brackets**: `df[[col1, col2]]`

### `df[[...]].isna()` returns a True/False table

In [23]:
df[["Spending2020", "Spending2021"]].isna()

     Spending2020  Spending2021
0           False         False
1           False         False
2           False         False
3           False         False
4           False         False
..            ...           ...
214          True         False
215         False         False
216         False         False
217         False         False
218         False         False

[219 rows x 2 columns]

### Count missing values for each column using `sum()`

In [24]:
df[["Spending2020", "Spending2021"]].isna().sum()

Spending2020    7
Spending2021    5
dtype: int64

In [ ]:
df[["Spending2020", "Spending2021", "Income", "College"]].isna().sum()

Spending2020    7
Spending2021    5
Income          0
College         0
dtype: int64

### Which columns have missing values? (optional; you may skip this)

In [25]:
# Only show columns with at least 1 missing value
df.isna().sum()[df.isna().sum() > 0]

Spending2020    7
Spending2021    5
dtype: int64

## Remove missing values with `dropna()`

✅ **Key point:** `dropna()` does **NOT** change the original DataFrame (`df`) by default.  
It **returns a NEW DataFrame** with missing values removed.

### Drop rows that have ANY missing value (in any column)

In [26]:
df #our dataframe (custom dataframe)

,CustID,Sex,Race,BirthDate,College,HouseholdSize,ZipCode,Income,Spending2020,Spending2021,NumOfOrders,DaysSinceLast,Satisfaction,Channel
0,1530016,Female,Black,12/16/1986,Yes,5,90047,53000,287.0,241.0,3,101,Very Dissatisfied,SM
1,1531136,Male,White,5/9/1993,Yes,5,90026,94000,1227.0,843.0,12,262,Neutral,TV
2,1532160,Male,Black,5/22/1966,Yes,2,90027,64000,523.0,719.0,9,122,Very Satisfied,TV
3,1532307,Male,White,9/16/1964,Yes,4,90029,60000,516.0,582.0,13,129,Very Dissatisfied,SM
4,1532356,Female,Hispanic,7/15/1964,No,5,90017,47000,555.0,845.0,7,97,Very Dissatisfied,Web
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,1578525,Male,Hispanic,12/12/1963,Yes,1,90005,82000,NaN,1121.0,25,302,Somewhat Satisfied,Web
215,1579349,Male,Asian,12/19/1980,Yes,1,90010,49000,217.0,397.0,10,200,Somewhat Satisfied,Web
216,1579389,Female,American Indian,5/21/2000,Yes,1,90009,50000,625.0,514.0,10,233,Somewhat Dissatisfied,Referral
217,1579857,Female,White,1/26/1991,Yes,1,90055,52000,325.0,586.0,13,219,Somewhat Dissatisfied,Referral
218,1579979,Male,White,7/5/1999,Yes,5,90043,102000,1080.0,926.0,10,113,Somewhat Satisfied,SM

In [27]:
df_drop_any = df.dropna()

df.shape, df_drop_any.shape

((219, 14), (208, 14))

Prove the original `df` is still intact:

In [28]:
df.shape

(219, 14)

### Drop rows only if specific columns are missing (recommended)

Example: drop rows where `Spending2020` OR `Spending2021` is missing.

In [30]:
#Drop/remove rows where spending2020 is missing
df_drop_2020 = df.dropna (subset = ["Spending2020"])
df_drop_2020.shape

(212, 14)

In [31]:
#Drop/remove rows where Spending2020 or Spending2021 is missing

df_drop_spend = df.dropna(subset=["Spending2020", "Spending2021"])

df.shape, df_drop_spend.shape

((219, 14), (208, 14))

Prove again the original `df` is unchanged:

In [ ]:
df.shape

(219, 14)

## Replace missing values with `fillna()` (use the mean)

✅ **Key point:** fillna() replace missing values with the value provided to fillna(). `fillna()` does **NOT** change the original DataFrame (`df`) by default (case 0)
To change data (orginal dataframe), you must either:
- **assign the result back**, (case 1) or
- use **`inplace=True`** (case 2)

We will show **three cases**.

### Case 0) `fillna()` without assignment (original `df` does NOT change)

First compute the mean (Pandas ignores NaN automatically):

In [32]:
mean_2021 = df["Spending2021"].mean()
mean_2021

np.float64(648.607476635514)

In [34]:
# Missing values before
df["Spending2021"].isna().sum()

np.int64(5)

In [36]:
# Fill missing values (but do NOT assign back)
temp = df["Spending2021"].fillna(mean_2021)     #does not update/change the orginal dataframe, df
                                                #temp has a new dataframe where all the rows with missing valus removed!

# Missing values in the new result
temp.isna().sum()

np.int64(0)

In [ ]:
# Prove original df is unchanged
df["Spending2021"].isna().sum()

np.int64(5)

✅ **Key point (Case 0):** `fillna()` returns a new result, but **does not change `df`** unless you assign it back (or use `inplace=True`).

### Case 1) Assign the result back (the original DataFrame df changes)

To keep the original `df` safe, use a copy:

In [40]:
df_case1 = df.copy()  #I do not want to change the orginal data frame df.
                      # I make the copy --> df_case1

# Missing values before
df_case1["Spending2021"].isna().sum()

np.int64(5)

In [41]:
mean_2021_case1 = df_case1["Spending2021"].mean()

# Assign the result back (this changes df_case1)
df_case1["Spending2021"] = df_case1["Spending2021"].fillna(mean_2021_case1) # note that df_case1 (spending2021) has been updated

# Missing values after
df_case1["Spending2021"].isna().sum()

np.int64(0)

✅ **Key point (Case 1):** The DataFrame changes because you **assign the result back**.

### Case 2) Use `inplace=True` (the DataFrame changes)

Again, use a copy:

In [45]:
df_case2 = df.copy()

# Missing values before
df_case2["Spending2021"].isna().sum()

np.int64(5)

In [47]:
mean_2021_case2 = df_case2["Spending2021"].mean()

# inplace=True changes df_case2 directly
df_case2.fillna(mean_2021_case2, inplace = True) #inplace = True --> it update the orginal dataframe, df_case2

# Missing values after
df_case2["Spending2021"].isna().sum()

np.int64(0)

✅ **Key point (Case 2):** The DataFrame changes because `inplace=True` modifies it directly.

## Fill multiple columns at once (each column uses its own mean)

✅ Multiple columns must use **double square brackets**.

In [ ]:
df_fill_means = df.copy()

cols = ["Spending2020", "Spending2021"]

# Each column is filled using its own mean
df_fill_means[cols] = df_fill_means[cols].fillna(df_fill_means[cols].mean())

df_fill_means[cols].isna().sum()

# ✅ Practice (Topic: Missing values)

Try these first. **Answers are shown right below each question.**

### Q1) Show the first 10 True/False results for missing values in `Spending2020`.

**Answer**

In [ ]:
df["Spending2020"].isna().head(10)

### Q2) Count how many missing values are in `Spending2020`.

**Answer**

In [ ]:
df["Spending2020"].isna().sum()

### Q3) Show the first 10 rows of the missing-value table for `Spending2020` and `Spending2021`.

✅ Use **double square brackets**.

**Answer**

In [ ]:
df[["Spending2020", "Spending2021"]].isna().head(10)

### Q4) Count missing values in `Spending2020` and `Spending2021`.

**Answer**

In [ ]:
df[["Spending2020", "Spending2021"]].isna().sum()

### Q5) Create `df_drop_spend` that drops rows if `Spending2020` or `Spending2021` is missing. Show both shapes.

**Answer**

In [ ]:
df_drop_spend = df.dropna(subset=["Spending2020", "Spending2021"])

df.shape, df_drop_spend.shape

### Q6) Fill missing values in `Spending2021` using the mean, but do NOT assign back. Prove `df` is unchanged.

**Answer**

In [ ]:
mean_2021 = df["Spending2021"].mean()
temp = df["Spending2021"].fillna(mean_2021)

# df is unchanged
df["Spending2021"].isna().sum()

### Q7) Create `df_fill_mean_2021` where missing `Spending2021` values are replaced with the mean (using assignment). Verify no missing values remain.

**Answer**

In [ ]:
df_fill_mean_2021 = df.copy()
mean_2021 = df_fill_mean_2021["Spending2021"].mean()
df_fill_mean_2021["Spending2021"] = df_fill_mean_2021["Spending2021"].fillna(mean_2021)

df_fill_mean_2021["Spending2021"].isna().sum()

### Q8) Fill missing values in BOTH `Spending2020` and `Spending2021` using their column means. Verify missing counts.

**Answer**

In [ ]:
df_fill_means = df.copy()
cols = ["Spending2020", "Spending2021"]
df_fill_means[cols] = df_fill_means[cols].fillna(df_fill_means[cols].mean())

df_fill_means[cols].isna().sum()

## Summary

- `isna()` returns **True/False** to show missing values.
- `dropna()` returns a **new DataFrame** (original `df` is unchanged unless you reassign).
- `fillna()` returns a **new result** unless you **assign back** or use **`inplace=True`**.