# Pandas Lecture 2 (Sections 3–4)

This lecture covers:
- **Section 3:** Column subsetting (single column, multiple columns)
- **Section 4:** Row subsetting using **boolean filters**

We will use the same `customer.csv` dataset.

## Setup: Read `customer.csv` and do a quick check

(If you already loaded `df` in Lecture 1, you can skip this setup section.)

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

# In Colab, replace with your Drive path, for example:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Teaching/BDA6140/GitHub/BDA6140-Spring-2026/Python-Code/Pandas-Data-Management/customer.csv")


df #df is a dataframe (customer dataframe)
   #df is a reference variable pointing to the data object (shown belw) whose data type is a dataframe

,CustID,Sex,Race,BirthDate,College,HouseholdSize,ZipCode,Income,Spending2020,Spending2021,NumOfOrders,DaysSinceLast,Satisfaction,Channel
0,1530016,Female,Black,12/16/1986,Yes,5,90047,53000,287.0,241.0,3,101,Very Dissatisfied,SM
1,1531136,Male,White,5/9/1993,Yes,5,90026,94000,1227.0,843.0,12,262,Neutral,TV
2,1532160,Male,Black,5/22/1966,Yes,2,90027,64000,523.0,719.0,9,122,Very Satisfied,TV
3,1532307,Male,White,9/16/1964,Yes,4,90029,60000,516.0,582.0,13,129,Very Dissatisfied,SM
4,1532356,Female,Hispanic,7/15/1964,No,5,90017,47000,555.0,845.0,7,97,Very Dissatisfied,Web
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,1578525,Male,Hispanic,12/12/1963,Yes,1,90005,82000,NaN,1121.0,25,302,Somewhat Satisfied,Web
215,1579349,Male,Asian,12/19/1980,Yes,1,90010,49000,217.0,397.0,10,200,Somewhat Satisfied,Web
216,1579389,Female,American Indian,5/21/2000,Yes,1,90009,50000,625.0,514.0,10,233,Somewhat Dissatisfied,Referral
217,1579857,Female,White,1/26/1991,Yes,1,90055,52000,325.0,586.0,13,219,Somewhat Dissatisfied,Referral
218,1579979,Male,White,7/5/1999,Yes,5,90043,102000,1080.0,926.0,10,113,Somewhat Satisfied,SM

In [3]:
# (rows, columns)
df.shape

(219, 14)

In [4]:
# how many rows (customers)
len(df)

219

In [5]:
# Quick numeric summary (Pandas automatically summarizes numeric columns)
df.describe()

,CustID,HouseholdSize,ZipCode,Income,Spending2020,Spending2021,NumOfOrders,DaysSinceLast
count,2.190000e+02,219.000000,219.000000,219.000000,212.000000,214.000000,219.000000,219.000000
mean,1.557781e+06,3.086758,90034.068493,73036.529680,644.962264,648.607477,10.844749,184.958904
std,1.424019e+04,1.429300,18.970519,24060.293889,396.516608,348.058526,9.329523,100.830374
min,1.530016e+06,1.000000,90001.000000,31000.000000,42.000000,50.000000,1.000000,6.000000
25%,1.546122e+06,2.000000,90018.000000,54000.000000,331.750000,372.500000,4.000000,102.000000
50%,1.557181e+06,3.000000,90032.000000,70000.000000,587.500000,626.000000,9.000000,181.000000
75%,1.571437e+06,4.000000,90050.000000,91500.000000,883.250000,943.250000,15.000000,266.000000
max,1.579979e+06,5.000000,90068.000000,167000.000000,1851.000000,1250.000000,89.000000,360.000000

# Section 3. Column subsetting (single column, multiple columns)

## 3.1 Single-column subsetting

In [6]:
# example:
df["Income"] # returns a single column with the data type Series

0       53000
1       94000
2       64000
3       60000
4       47000
        ...
214     82000
215     49000
216     50000
217     52000
218    102000
Name: Income, Length: 219, dtype: int64

In [7]:
df[['Income']] # returns a single column with data type dataframe

     Income
0     53000
1     94000
2     64000
3     60000
4     47000
..      ...
214   82000
215   49000
216   50000
217   52000
218  102000

[219 rows x 1 columns]

In [8]:
df['Spending2020'] #returns a single column (spending2020)

0       287.0
1      1227.0
2       523.0
3       516.0
4       555.0
        ...
214       NaN
215     217.0
216     625.0
217     325.0
218    1080.0
Name: Spending2020, Length: 219, dtype: float64

In [9]:
df['DaysSinceLast'] # --> returns a series
#df[['DaysSInceLast']] --> returns a dataframe

0      101
1      262
2      122
3      129
4       97
      ...
214    302
215    200
216    233
217    219
218    113
Name: DaysSinceLast, Length: 219, dtype: int64

## 3.2 Single-column subsetting + basic statistics

In [10]:
df["Income"].min()

31000

In [ ]:
df["Income"].max()

167000

In [11]:
df["Income"].mean()

np.float64(73036.5296803653)

In [ ]:
df["Income"].sum()

np.int64(15995000)

You can also use **double brackets** to keep it as a one-column **DataFrame** (2D):

In [ ]:
df[["Income"]].min()

Income    31000
dtype: int64

In [ ]:
df[["Income"]].max()

Income    167000
dtype: int64

In [ ]:
df['DaysSinceLast'].mean()  #returns the average values in the column "DaysSinceLast"

np.float64(184.95890410958904)

## 3.3 Multiple-column subsetting

Syntax:  `df[[col1, col2, ...]]`

In [13]:
df_small_col = df[["CustID", "Income", "Channel"]] #returns a dataframe with three columns
df_small_col

      CustID  Income   Channel
0    1530016   53000        SM
1    1531136   94000        TV
2    1532160   64000        TV
3    1532307   60000        SM
4    1532356   47000       Web
..       ...     ...       ...
214  1578525   82000       Web
215  1579349   49000       Web
216  1579389   50000  Referral
217  1579857   52000  Referral
218  1579979  102000        SM

[219 rows x 3 columns]

In [14]:
#Using multpe column subsetting --> dispaly College, Race, Satisfaction columns

df_mul = df[["College", "Race", "Satisfaction"]]
df_mul

    College             Race           Satisfaction
0       Yes            Black      Very Dissatisfied
1       Yes            White                Neutral
2       Yes            Black         Very Satisfied
3       Yes            White      Very Dissatisfied
4        No         Hispanic      Very Dissatisfied
..      ...              ...                    ...
214     Yes         Hispanic     Somewhat Satisfied
215     Yes            Asian     Somewhat Satisfied
216     Yes  American Indian  Somewhat Dissatisfied
217     Yes            White  Somewhat Dissatisfied
218     Yes            White     Somewhat Satisfied

[219 rows x 3 columns]

## ✅ Practice (Section 3: Column subsetting)

### Q1) Series vs DataFrame (single column)
Check the type of:
- `df["Income"]`
- `df[["Income"]]`

**Answer**
```python
print(type(df["Income"]))     # Series
print(type(df[["Income"]]))   # DataFrame
```

### Q2) Max and average of a column
Find:
1. The **maximum** value of `Spending2020`
2. The **average (mean)** value of `Spending2020`

**Answer**
```python
df["Spending2020"].max()
df["Spending2020"].mean()
```

# Section 4. Row subsetting using boolean filters

## What is Row Filtering Using Boolean Expressions?

**Row filtering** (also called **boolean indexing**) is a way to select only the rows from a DataFrame that satisfy a given condition.

When you write a comparison like `df["Income"] >= 80000`, Pandas evaluates it for **every row** and returns a **Series of True/False values** (one per row). When you place that Series inside `df[...]`, Pandas keeps only the rows where the value is `True` and drops the rows where it is `False`.

**Typical syntax:**

```
df[ boolean_expression ]
```

How it works step-by-step:

| Step | Code | Result |
|------|------|--------|
| 1. Write a condition | `df["Income"] >= 80000` | A Series of `True` / `False` for every row |
| 2. Pass it into `df[...]` | `df[ df["Income"] >= 80000 ]` | A new DataFrame containing **only** the rows where the condition is `True` |

**Think of it as:** `df[ True/False for every row ]` → returns only the `True` rows.

In [15]:
df.head()

,CustID,Sex,Race,BirthDate,College,HouseholdSize,ZipCode,Income,Spending2020,Spending2021,NumOfOrders,DaysSinceLast,Satisfaction,Channel
0,1530016,Female,Black,12/16/1986,Yes,5,90047,53000,287.0,241.0,3,101,Very Dissatisfied,SM
1,1531136,Male,White,5/9/1993,Yes,5,90026,94000,1227.0,843.0,12,262,Neutral,TV
2,1532160,Male,Black,5/22/1966,Yes,2,90027,64000,523.0,719.0,9,122,Very Satisfied,TV
3,1532307,Male,White,9/16/1964,Yes,4,90029,60000,516.0,582.0,13,129,Very Dissatisfied,SM
4,1532356,Female,Hispanic,7/15/1964,No,5,90017,47000,555.0,845.0,7,97,Very Dissatisfied,Web

In [16]:
boolean_exp = df["Income"] >= 80000  #--> boolean expression/filter
boolean_exp

0      False
1       True
2      False
3      False
4      False
       ...
214     True
215    False
216    False
217    False
218     True
Name: Income, Length: 219, dtype: bool

In [17]:
df[ boolean_exp  ]

,CustID,Sex,Race,BirthDate,College,HouseholdSize,ZipCode,Income,Spending2020,Spending2021,NumOfOrders,DaysSinceLast,Satisfaction,Channel
1,1531136,Male,White,5/9/1993,Yes,5,90026,94000,1227.0,843.0,12,262,Neutral,TV
6,1533017,Female,Hispanic,5/14/1985,Yes,3,90063,84000,229.0,153.0,2,144,Very Satisfied,Web
10,1533791,Male,White,10/27/1999,Yes,1,90060,97000,828.0,1028.0,17,110,Very Dissatisfied,Web
12,1534502,Male,Hispanic,12/26/1989,Yes,2,90056,114000,938.0,665.0,7,262,Very Dissatisfied,TV
13,1534928,Male,Hispanic,1/18/1959,Yes,5,90033,96000,631.0,796.0,13,68,Neutral,Referral
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,1576984,Male,Black,2/20/1966,Yes,4,90050,87000,152.0,247.0,6,148,Neutral,Web
210,1577691,Male,Hispanic,3/27/1976,Yes,5,90001,97000,70.0,89.0,2,205,Somewhat Satisfied,TV
211,1577940,Female,Black,2/27/1973,Yes,5,90019,94000,634.0,1206.0,18,181,Somewhat Satisfied,Web
214,1578525,Male,Hispanic,12/12/1963,Yes,1,90005,82000,NaN,1121.0,25,302,Somewhat Satisfied,Web
218,1579979,Male,White,7/5/1999,Yes,5,90043,102000,1080.0,926.0,10,113,Somewhat Satisfied,SM

In [18]:
df[ df["Income"] >= 80000  ]

,CustID,Sex,Race,BirthDate,College,HouseholdSize,ZipCode,Income,Spending2020,Spending2021,NumOfOrders,DaysSinceLast,Satisfaction,Channel
1,1531136,Male,White,5/9/1993,Yes,5,90026,94000,1227.0,843.0,12,262,Neutral,TV
6,1533017,Female,Hispanic,5/14/1985,Yes,3,90063,84000,229.0,153.0,2,144,Very Satisfied,Web
10,1533791,Male,White,10/27/1999,Yes,1,90060,97000,828.0,1028.0,17,110,Very Dissatisfied,Web
12,1534502,Male,Hispanic,12/26/1989,Yes,2,90056,114000,938.0,665.0,7,262,Very Dissatisfied,TV
13,1534928,Male,Hispanic,1/18/1959,Yes,5,90033,96000,631.0,796.0,13,68,Neutral,Referral
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,1576984,Male,Black,2/20/1966,Yes,4,90050,87000,152.0,247.0,6,148,Neutral,Web
210,1577691,Male,Hispanic,3/27/1976,Yes,5,90001,97000,70.0,89.0,2,205,Somewhat Satisfied,TV
211,1577940,Female,Black,2/27/1973,Yes,5,90019,94000,634.0,1206.0,18,181,Somewhat Satisfied,Web
214,1578525,Male,Hispanic,12/12/1963,Yes,1,90005,82000,NaN,1121.0,25,302,Somewhat Satisfied,Web
218,1579979,Male,White,7/5/1999,Yes,5,90043,102000,1080.0,926.0,10,113,Somewhat Satisfied,SM

## 4.1 Boolean row filtering (very important)

This is how we "filter rows" based on conditions.

**Q: What are the customers whose `Income` is greater than or equal to 80,000?**

In [ ]:
# Customers with high income
high_income = df[df["Income"] >= 80000]
high_income.head()

,CustID,Sex,Race,BirthDate,College,HouseholdSize,ZipCode,Income,Spending2020,Spending2021,NumOfOrders,DaysSinceLast,Satisfaction,Channel
1,1531136,Male,White,5/9/1993,Yes,5,90026,94000,1227.0,843.0,12,262,Neutral,TV
6,1533017,Female,Hispanic,5/14/1985,Yes,3,90063,84000,229.0,153.0,2,144,Very Satisfied,Web
10,1533791,Male,White,10/27/1999,Yes,1,90060,97000,828.0,1028.0,17,110,Very Dissatisfied,Web
12,1534502,Male,Hispanic,12/26/1989,Yes,2,90056,114000,938.0,665.0,7,262,Very Dissatisfied,TV
13,1534928,Male,Hispanic,1/18/1959,Yes,5,90033,96000,631.0,796.0,13,68,Neutral,Referral

In [ ]:
#How many customers whose Income is greater than or equal to 80k?
high_income.shape

(81, 14)

In [ ]:
len(high_income)

81

In [ ]:
df[df["Income"] >= 80000].shape

(81, 14)

In [ ]:
len(df[df["Income"] >= 80000])

81

**Q: What are the customers whose `DaysSinceLast` is less than or equal to 30 (i.e., purchased very recently)?**

In [ ]:
df['DaysSinceLast'] <= 30  #boolean expression

0      False
1      False
2      False
3      False
4      False
       ...
214    False
215    False
216    False
217    False
218    False
Name: DaysSinceLast, Length: 219, dtype: bool

In [19]:
# Customers who purchased recently (small DaysSinceLast)
recent = df[df["DaysSinceLast"] <= 30]
recent.head()

,CustID,Sex,Race,BirthDate,College,HouseholdSize,ZipCode,Income,Spending2020,Spending2021,NumOfOrders,DaysSinceLast,Satisfaction,Channel
11,1533917,Female,Black,3/3/1993,Yes,3,90045,64000,768.0,915.0,15,19,Very Satisfied,Referral
28,1540183,Male,White,2/27/1991,Yes,1,90066,91000,1018.0,800.0,10,6,Somewhat Satisfied,Web
31,1540604,Female,White,4/22/1970,Yes,3,90011,73000,428.0,539.0,5,12,Very Satisfied,Web
38,1543502,Male,Hispanic,4/6/1982,Yes,2,90007,55000,461.0,563.0,12,17,Somewhat Satisfied,SM
48,1544628,Male,White,9/15/1983,Yes,3,90021,69000,215.0,173.0,3,11,Somewhat Satisfied,Web

In [ ]:
#Midterm Exam question
# What are the customers whose satisfaction level is "Very Satified"
#first step is to write a boolean expression:
df['Satisfaction'] == "Very Satisfied "

#second step is to apply df to the boolean expression to get a dataframe
very_sat_cus = df[ df['Satisfaction'] == "Very Satisfied"]
very_sat_cus.shape

#How many "very satifised customers"

(49, 14)

## 4.2 Multiple conditions
- Use `&` for AND, `|` for OR, `~` for NOT
- Put each condition in parentheses

### Boolean Operator Reference Tables

Below are the truth tables for the three logical operators used in Pandas row filtering.

**AND (`&`)** — Both conditions must be `True`

| A | B | A & B |
|---|---|-------|
| True | True | **True** |
| True | False | False |
| False | True | False |
| False | False | False |

**OR (`|`)** — At least one condition must be `True`

| A | B | A \| B |
|---|---|--------|
| True | True | **True** |
| True | False | **True** |
| False | True | **True** |
| False | False | False |

**NOT (`~`)** — Flips `True` ↔ `False`

| A | ~A |
|---|-----|
| True | False |
| False | **True** |

**Q: What are the customers who are `Female` AND have `College` = `Yes`?**

In [20]:
df["Sex"] == "Female" & df["College"] == "Yes" # Syntax Error!!!!!!! boolean expression --> use ()!!!!!!!!!!!!!!!
#See the solution below!!!

TypeError: Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]

In [21]:
(df["Sex"] == "Female") & (df["College"] == "Yes")

0       True
1      False
2      False
3      False
4      False
       ...
214    False
215    False
216     True
217     True
218    False
Length: 219, dtype: bool

In [22]:
# Female AND College = Yes
female_college = df[(df["Sex"] == "Female") & (df["College"] == "Yes")]
female_college.head()

,CustID,Sex,Race,BirthDate,College,HouseholdSize,ZipCode,Income,Spending2020,Spending2021,NumOfOrders,DaysSinceLast,Satisfaction,Channel
0,1530016,Female,Black,12/16/1986,Yes,5,90047,53000,287.0,241.0,3,101,Very Dissatisfied,SM
6,1533017,Female,Hispanic,5/14/1985,Yes,3,90063,84000,229.0,153.0,2,144,Very Satisfied,Web
8,1533697,Female,Asian,10/8/1974,Yes,3,90038,42000,300.0,247.0,3,238,Very Satisfied,Web
11,1533917,Female,Black,3/3/1993,Yes,3,90045,64000,768.0,915.0,15,19,Very Satisfied,Referral
14,1535063,Female,White,12/17/1982,Yes,3,90024,42000,341.0,313.0,4,300,Very Dissatisfied,TV

In [ ]:
#How many customers who are female and have college degree
female_college.shape

(67, 14)

In [ ]:
len(female_college)

67

**Q: What are the customers who are `Female` OR have `College` = `Yes` (either condition is enough)?**

In [ ]:
# Female OR College = Yes (either condition is enough)
female_or_college = df[(df["Sex"] == "Female") | (df["College"] == "Yes")]
female_or_college.head()

,CustID,Sex,Race,BirthDate,College,HouseholdSize,ZipCode,Income,Spending2020,Spending2021,NumOfOrders,DaysSinceLast,Satisfaction,Channel
0,1530016,Female,Black,12/16/1986,Yes,5,90047,53000,287.0,241.0,3,101,Very Dissatisfied,SM
1,1531136,Male,White,5/9/1993,Yes,5,90026,94000,1227.0,843.0,12,262,Neutral,TV
2,1532160,Male,Black,5/22/1966,Yes,2,90027,64000,523.0,719.0,9,122,Very Satisfied,TV
3,1532307,Male,White,9/16/1964,Yes,4,90029,60000,516.0,582.0,13,129,Very Dissatisfied,SM
4,1532356,Female,Hispanic,7/15/1964,No,5,90017,47000,555.0,845.0,7,97,Very Dissatisfied,Web

In [ ]:
# How many
female_or_college.shape

(199, 14)

**Q: What are the customers whose `Income` is between 50,000 and 80,000 (inclusive)?**

In [ ]:
# Income between 50000 and 80000 (inclusive)
# Use two comparisons + & (AND)
mid_income = df[(df["Income"] >= 50000) & (df["Income"] <= 80000)]
mid_income.head()

**Q: What are the customers whose `Channel` is `Web` OR `TV`?**

In [ ]:
# Channel is Web OR TV (same idea as "isin", but using OR)
selected_channels = df[(df["Channel"] == "Web") | (df["Channel"] == "TV")]
selected_channels.head()

**Q: What are the customers who do NOT have `College` = `Yes` (i.e., customers without a college education)?**

In [ ]:
~(df['College'] == 'Yes')

0      False
1      False
2      False
3      False
4       True
       ...
214    False
215    False
216    False
217    False
218    False
Name: College, Length: 219, dtype: bool

In [ ]:
# NOT condition: customers who are NOT in College = Yes
not_college_yes = df[~(df["College"] == "Yes")]
not_college_yes.head()

## ✅ Practice (Section 4.1 & 4.2: Boolean Row Filtering)

These are a little harder. **Answers are shown right below each question.**

### Q1) AND condition
**What are the customers whose `Spending2021` is greater than 1,000 AND whose `Satisfaction` is `Very Dissatisfied`?**

**Answer**
```python
df[(df["Spending2021"] > 1000) & (df["Satisfaction"] == "Very Dissatisfied")].head()
```

### Q2) OR condition
**What are the customers whose `HouseholdSize` is 1 OR whose `HouseholdSize` is 5?**

**Answer**
```python
df[(df["HouseholdSize"] == 1) | (df["HouseholdSize"] == 5)].head()
```

### Q3) NOT condition + AND
**What are the customers who are NOT `Male` AND whose `NumOfOrders` is greater than or equal to 20?**

**Answer**
```python
df[~(df["Sex"] == "Male") & (df["NumOfOrders"] >= 20)].head()
```

### Q4) Combining AND + OR (multiple conditions)
**What are the customers whose `Income` is between 50,000 and 80,000 (inclusive) AND who were referred by `Web` or `TV`?**

**Answer**
```python
df[
    ((df["Channel"] == "Web") | (df["Channel"] == "TV"))
    & (df["Income"] >= 50000)
    & (df["Income"] <= 80000)
].head()
```

## 4.3 Row-Column Subsetting with `iloc` and `loc`

So far we have learned:
- **Column subsetting:** `df["col"]` or `df[["col1", "col2"]]` → select columns
- **Row subsetting:** `df[boolean_expression]` → filter rows

But what if you want to select **specific rows AND specific columns at the same time**?

Pandas provides two indexers for this:

| Indexer | Selects by | Syntax |
|---------|-----------|--------|
| `df.iloc[row, col]` | **Integer position** (0, 1, 2, …) | `df.iloc[row_position, col_position]` |
| `df.loc[row, col]` | **Label / index name** | `df.loc[row_label, col_name]` |

**Think of it as:**
- **`iloc`** = **i**nteger **loc**ation (use numbers)
- **`loc`** = **l**abel-based **loc**ation (use index labels and column names)

### 4.3.1 `iloc` — Selection by integer position

**Q: What is the value in the 1st row and 1st column of the DataFrame (i.e., position [0, 0])?**

In [ ]:
df.head()

,CustID,Sex,Race,BirthDate,College,HouseholdSize,ZipCode,Income,Spending2020,Spending2021,NumOfOrders,DaysSinceLast,Satisfaction,Channel
0,1530016,Female,Black,12/16/1986,Yes,5,90047,53000,287.0,241.0,3,101,Very Dissatisfied,SM
1,1531136,Male,White,5/9/1993,Yes,5,90026,94000,1227.0,843.0,12,262,Neutral,TV
2,1532160,Male,Black,5/22/1966,Yes,2,90027,64000,523.0,719.0,9,122,Very Satisfied,TV
3,1532307,Male,White,9/16/1964,Yes,4,90029,60000,516.0,582.0,13,129,Very Dissatisfied,SM
4,1532356,Female,Hispanic,7/15/1964,No,5,90017,47000,555.0,845.0,7,97,Very Dissatisfied,Web

In [23]:
# Single element: row 0, column 0
df.iloc[0, 0]

np.int64(1530016)

**Q: What are the first 5 rows and first 3 columns of the DataFrame?**

In [24]:
# First 5 rows, first 3 columns (using slicing)
df.iloc[0:5, 0:3]

    CustID     Sex      Race
0  1530016  Female     Black
1  1531136    Male     White
2  1532160    Male     Black
3  1532307    Male     White
4  1532356  Female  Hispanic

**Q: What are the values in rows 0, 5, and 10 for columns at positions 0, 7, and 13 (`CustID`, `Income`, and `Channel`)?**

In [ ]:
df.head()

,CustID,Sex,Race,BirthDate,College,HouseholdSize,ZipCode,Income,Spending2020,Spending2021,NumOfOrders,DaysSinceLast,Satisfaction,Channel
0,1530016,Female,Black,12/16/1986,Yes,5,90047,53000,287.0,241.0,3,101,Very Dissatisfied,SM
1,1531136,Male,White,5/9/1993,Yes,5,90026,94000,1227.0,843.0,12,262,Neutral,TV
2,1532160,Male,Black,5/22/1966,Yes,2,90027,64000,523.0,719.0,9,122,Very Satisfied,TV
3,1532307,Male,White,9/16/1964,Yes,4,90029,60000,516.0,582.0,13,129,Very Dissatisfied,SM
4,1532356,Female,Hispanic,7/15/1964,No,5,90017,47000,555.0,845.0,7,97,Very Dissatisfied,Web

In [ ]:
# Specific rows and columns by position (using lists)
df.iloc[[0, 5, 10], [0, 7, 13]]

     CustID  Income Channel
0   1530016   53000      SM
5   1532387   67000      SM
10  1533791   97000     Web

**Q: What are all columns for the first 3 rows?**

*Tip:* Use `:` to mean "all" for either rows or columns.

In [ ]:
# All columns for the first 3 rows
df.iloc[0:3, :]

,CustID,Sex,Race,BirthDate,College,HouseholdSize,ZipCode,Income,Spending2020,Spending2021,NumOfOrders,DaysSinceLast,Satisfaction,Channel
0,1530016,Female,Black,12/16/1986,Yes,5,90047,53000,287.0,241.0,3,101,Very Dissatisfied,SM
1,1531136,Male,White,5/9/1993,Yes,5,90026,94000,1227.0,843.0,12,262,Neutral,TV
2,1532160,Male,Black,5/22/1966,Yes,2,90027,64000,523.0,719.0,9,122,Very Satisfied,TV

### 4.3.2 `loc` — Selection by label / column name

**Q: What are the `CustID`, `Income`, and `Channel` values for the row with index label 0?**

In [ ]:
# Single row by index label, specific columns by name
df.loc[0, ["CustID", "Income", "Channel"]]

CustID     1530016
Income       53000
Channel         SM
Name: 0, dtype: object

**Q: What are the `Sex`, `Income`, and `Satisfaction` values for rows with index labels 0 through 4?**

*Note:* Unlike `iloc`, `loc` slicing is **inclusive** on both ends — `0:4` returns rows 0, 1, 2, 3, **and** 4.

In [26]:
# Rows 0 to 4 (inclusive!), selected columns by name
df.loc[0:4, ["Sex","Income", "Satisfaction"]]

      Sex  Income       Satisfaction
0  Female   53000  Very Dissatisfied
1    Male   94000            Neutral
2    Male   64000     Very Satisfied
3    Male   60000  Very Dissatisfied
4  Female   47000  Very Dissatisfied

In [ ]:
#please use idential expression using iloc (good exam question)
df.iloc[0:5    , [1,7, 12]  ]

      Sex  Income       Satisfaction
0  Female   53000  Very Dissatisfied
1    Male   94000            Neutral
2    Male   64000     Very Satisfied
3    Male   60000  Very Dissatisfied
4  Female   47000  Very Dissatisfied

**Q: What are the `CustID` and `Income` values for all rows (using `loc`)?**

In [ ]:
# All rows, selected columns by name
df.loc[:, ["CustID", "Income"]].head()

### 4.3.3 Combining boolean filters with `loc`

You can also use a **boolean expression** as the row selector inside `loc` to filter rows AND select specific columns at the same time.

```
df.loc[boolean_expression, [col1, col2, ...]]
```

**Q: For customers whose `Income` is greater than or equal to 100,000, what are their `CustID`, `Income`, and `Channel` values?**

In [ ]:
# Boolean filter + column selection using loc
df.loc[df["Income"] >= 100000, ["CustID", "Income", "Channel"]].head()

     CustID  Income   Channel
12  1534502  114000        TV
30  1540539  100000       Web
32  1541742  106000  Referral
39  1543582  101000       Web
51  1545054  102000  Referral

**Q: For customers who are `Female` and have `Spending2021` greater than 800, what are their `CustID`, `Sex`, `Spending2021`, and `Satisfaction` values?**

In [ ]:
# Multiple boolean conditions + column selection
df.loc[(df["Sex"] == "Female") & (df["Spending2021"] > 800),  ["CustID", "Sex", "Spending2021", "Satisfaction"]]

      CustID     Sex  Spending2021           Satisfaction
4    1532356  Female         845.0      Very Dissatisfied
11   1533917  Female         915.0         Very Satisfied
26   1539995  Female         802.0     Somewhat Satisfied
37   1542818  Female         814.0                Neutral
50   1544764  Female         911.0     Somewhat Satisfied
55   1546138  Female        1125.0     Somewhat Satisfied
56   1546179  Female         850.0     Somewhat Satisfied
58   1546623  Female        1038.0     Somewhat Satisfied
59   1546870  Female        1127.0         Very Satisfied
73   1550268  Female         862.0         Very Satisfied
87   1553405  Female        1193.0     Somewhat Satisfied
94   1553737  Female         867.0                Neutral
104  1555539  Female        1182.0         Very Satisfied
105  1555659  Female        1101.0         Very Satisfied
108  1556823  Female        1123.0     Somewhat Satisfied
114  1557697  Female         897.0     Somewhat Satisfied
125  1562348  Female         860.0                Neutral
147  1566529  Female        1105.0  Somewhat Dissatisfied
148  1567124  Female        1128.0                Neutral
149  1567193  Female         962.0  Somewhat Dissatisfied
152  1567389  Female         979.0         Very Satisfied
156  1568380  Female         963.0                Neutral
160  1569840  Female         823.0     Somewhat Satisfied
161  1570150  Female        1155.0         Very Satisfied
163  1571419  Female        1137.0         Very Satisfied
172  1573758  Female         986.0     Somewhat Satisfied
175  1574042  Female        1044.0     Somewhat Satisfied
182  1574841  Female        1122.0         Very Satisfied
192  1577940  Female        1206.0     Somewhat Satisfied
201  1574841  Female        1122.0         Very Satisfied
211  1577940  Female        1206.0     Somewhat Satisfied

### `iloc` vs `loc` — Quick Comparison

| Feature | `iloc` | `loc` |
|---------|--------|-------|
| Selects by | Integer position (0, 1, 2, …) | Label / column name |
| Slicing end | **Exclusive** (`0:3` → rows 0, 1, 2) | **Inclusive** (`0:3` → rows 0, 1, 2, 3) |
| Column reference | Column number (e.g., `7`) | Column name (e.g., `"Income"`) |
| Boolean filter as row selector | ❌ Not supported | ✅ Supported |

## ✅ Practice (Section 4.3: Row-Column Subsetting)

**Answers are shown right below each question.**

### Q1) `iloc` — Slice a block
**What are the values in rows 10 through 14 and columns at positions 1 through 4?**

**Answer**
```python
df.iloc[10:15, 1:5]
```

### Q2) `loc` — Select by name
**What are the `CustID`, `Race`, and `HouseholdSize` values for rows with index labels 0 through 9?**

**Answer**
```python
df.loc[0:9, ["CustID", "Race", "HouseholdSize"]]
```

### Q3) `loc` with a boolean filter
**For customers whose `Channel` is `Referral` and whose `DaysSinceLast` is less than or equal to 60, what are their `CustID`, `Income`, `DaysSinceLast`, and `Channel` values?**

**Answer**
```python
df.loc[
    (df["Channel"] == "Referral") & (df["DaysSinceLast"] <= 60),
    ["CustID", "Income", "DaysSinceLast", "Channel"]
].head()
```

### Q4) `iloc` — Pick specific rows and columns
**What are the values at rows 0, 50, 100, and 150 for the 1st, 8th, and 14th columns (positions 0, 7, and 13)?**

**Answer**
```python
df.iloc[[0, 50, 100, 150], [0, 7, 13]]
```